name: CMake

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  zephyr_sample:
    env:
      ZEPHYR_VERSION: 3.3.0
    runs-on: ubuntu-20.04
    container: 
      image:  zephyrprojectrtos/ci:v0.26.0
      options: --user root
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: CPPU Test dependencies
      run: apt-get update && apt install -y cpputest pkg-config gcc-multilib g++-multilib
    - name: Clone Zephyr RTOS
      run: |
            west init -m https://github.com/zephyrproject-rtos/zephyr --mr v${ZEPHYR_VERSION} zephyr \
            && cd zephyr \
            && west update
    - name: build
      run: | 
            cd zephyr \
            && west build ../examples/zephyr_posix --pristine --board native_posix_64
    - name: run
      run: ./build/zephyr/zephyr.exe


