name: CMake

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  zephyr:
    runs-on: ubuntu-20.04
    container: zephyrprojectrtos/zephyr-build
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Dependencies
      run: sudo apt install -y cpputest pkg-config gcc-multilib g++-multilib
