name: CMake

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  zephyr_sample:
    runs-on: ubuntu-20.04
    container: 
      image:  nordicplayground/nrfconnect-sdk:main
      options: --user root
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Dependencies
      run: apt install -y cpputest pkg-config gcc-multilib g++-multilib
    - name: build
      run: west build . --pristine --board native_posix_64 && ls
    - name: run
      run: ls


