name: CMake

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
    name: Build Zephyr example
    needs: build
    env:
      ZEPHYR_VERSION: 3.2.0
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-0.16.0/
    runs-on: ubuntu-20.04
    container: 
      image:  zephyrprojectrtos/ci:v0.26.0
      options: --user root
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: CPPU Test dependencies
      run: apt-get update && apt install -y cpputest pkg-config gcc-multilib g++-multilib
    - name: Clone Zephyr RTOS
      run: |
            west init -m https://github.com/zephyrproject-rtos/zephyr --mr v${ZEPHYR_VERSION} zephyr \
            && cd zephyr \
            && west update
    - name: build
      run: | 
            mkdir build \
            && cd zephyr \
            && west build ../examples/zephyr_posix --build-dir ../build --pristine --board native_posix_64 \
    - uses: actions/upload-artifact@master
      with:
        name: zephyr_bin
        path: build/zephyr/zephyr.exe
  zephyr_test:
    name: Run the zephyr example
    runs-on: ubuntu-20.04
    needs: zephyr_build
    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@master
      with:
        name: zephyr_bin
        path: build/zephyr/zephyr.exe
    - run: ./zephyr.exe

